### ISSUE TITLE
screenshots please

### ISSUE THREAD

**Issue by johnfelipe** [marfnk/android-continuous-voice#2]

**Comment by marfnk** [comment]
![screenshots_please_ _issue__2_ _marfnk_android-continuous-voice](https://cloud.githubusercontent.com/assets/1614863/8667449/5f8df228-2a00-11e5-9497-36c763716399.jpg)

**Comment by marfnk** [comment]
No. Just kiddin' - I will add some later ;)

**Comment by johnfelipe** [comment]
Jijiji, awsome, stay alert
